#!/bin/bash

printf "\ntaking ownership of /usr/local...\n"
sudo find /usr/local -type d -exec chown dev:staff {} +

printf "\nmaking all sub-directories writable: /usr/local...\n"
sudo find /usr/local -type d -exec chmod 0775 {} +

printf "\ndone.\n\n"

